/**:
  ros__parameters:
    rate: 50
    pole:
      latitude:   35.648474
      longitude:  128.399303
      altitude:   46.6
    lidar:
      px:           0.0 #[m]
      py:           0.0 #[m]
      pz:           4.0 #[m]
      heading_yaw:  132.7125 #[degrees]